// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodels

type CreateRoomInput struct {
	Title    string `json:"title"`
	HostName string `json:"hostName"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Vote     *int   `json:"vote"`
	IsAdmin  bool   `json:"isAdmin"`
}
