// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodels

type CreateRoomInput struct {
	Title    string `json:"title"`
	HostName string `json:"hostName"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	IsAdmin  bool   `json:"isAdmin"`
	RoomID   int    `json:"roomId"`
}

type CreateVoteInput struct {
	Vote   float64 `json:"vote"`
	UserID int     `json:"userId"`
	RoomID int     `json:"roomId"`
}

type GetRoomVotesInput struct {
	RoomID int `json:"roomId"`
}
