// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodels

type CreateRoomInput struct {
	Title string `json:"title"`
}

type Room struct {
	ID          int     `json:"id"`
	Title       string  `json:"title"`
	AverageVote float64 `json:"averageVote"`
}
